# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-18 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linguagem', models.CharField(max_length=100, verbose_name='Projeto:')),
                ('linhas_codigo', models.IntegerField(null=True)),
                ('total_linhas', models.IntegerField(null=True)),
                ('arquivos', models.IntegerField(null=True)),
                ('classes', models.IntegerField(null=True)),
                ('metodos', models.IntegerField(null=True)),
                ('complexidade_total', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('complexidade_metodo', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('complexidade_classe', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('complexidade_arquivo', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('taxa_duplicacao', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('taxa_divida_tecnica', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('total_codesmell', models.IntegerField(null=True)),
                ('total_problemas', models.IntegerField(null=True)),
                ('problemas_criticos', models.IntegerField(null=True)),
                ('problemas_importantes', models.IntegerField(null=True)),
                ('problemas_moderados', models.IntegerField(null=True)),
                ('problemas_normais', models.IntegerField(null=True)),
                ('problemas_simples', models.IntegerField(null=True)),
                ('taxa_comentarios', models.IntegerField(null=True)),
                ('data_revisao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linguagem', models.CharField(max_length=100, verbose_name='Linguagem:')),
                ('total_projetos', models.IntegerField(null=True)),
                ('linhas_codigo', models.IntegerField(null=True)),
                ('total_linhas', models.IntegerField(null=True)),
                ('arquivos', models.IntegerField(null=True)),
                ('classes', models.IntegerField(null=True)),
                ('metodos', models.IntegerField(null=True)),
                ('complexidade_total', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('complexidade_metodo', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('complexidade_classe', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('complexidade_arquivo', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('taxa_duplicacao', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('taxa_divida_tecnica', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('total_problemas', models.IntegerField(null=True)),
                ('problemas_criticos', models.IntegerField(null=True)),
                ('problemas_importantes', models.IntegerField(null=True)),
                ('problemas_moderados', models.IntegerField(null=True)),
                ('problemas_normais', models.IntegerField(null=True)),
                ('problemas_simples', models.IntegerField(null=True)),
                ('taxa_comentarios', models.IntegerField(null=True)),
                ('data_revisao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
