# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-29 03:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linguagem', models.CharField(max_length=100, verbose_name='Projeto:')),
                ('inserido_em', models.DateTimeField(auto_now_add=True)),
                ('monitorado', models.BooleanField(default=True)),
                ('repositorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Repositorio')),
            ],
        ),
    ]
